<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMchs0o1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMchs0o1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMchs0o1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMchs0o1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMchs0o1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mchs0o1',
    'container.build_id' => '25af9005',
    'container.build_time' => 1593606378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMchs0o1');
